### PR TITLE
feat: add automated browser auth v1

### PR DESCRIPTION
**Pull request by HBFLEX**
- added a new route '/authenticate_browser'
- registered the new route to the main app
- added the automation browser auth functionality.

### CODE REVIEW

**Review by KentChunga — CHANGES_REQUESTED** [review]
-  Everything seem to work just fine.
- But i would suggest that you consider ;
-- Making use of environment variables.
-- Defining the `initialize_webdriver`, `login_to_site`, and `is_login_successful` functions in the utils to keep the browser_auth_routes.py file more  concise.

**Comment by HBFLEX** [comment]
Alright I will do that 💯

**Review by HBFLEX — COMMENTED** [review]
successfully refactored the code with the requested changes

**Review by TgkCapture — APPROVED** [review]
Had to test from a different machine, but with the changes added after @KentChunga 's request seems okay, were good to go.

**Pull request merged**
